### ISSUE TITLE
Possible to get screenshot of 'Entire Screen' and as Png data

### ISSUE THREAD

**Issue by aredfox** [asafyish/screenshot-pool#1]
It's not clear to me how this module works, does it capture a website or url, or does it capture the screen?
Is it possible to get screenshot of 'Entire Screen' and as Png data, what is caontained in imgData, is it a base64 representation?

Thanks

**Comment by asafyish** [comment]
Hi,

This module works with a url, like you can see the 'capture' method.
It's possible to render a page using [data uri](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs).

The screenshot result is a base64 representation of a png containing the inner parts of the window, without the chrome around it.

**Comment by aredfox** [comment]
Ok thanks for your clear answer. Looks like i'll have to find another solution then, as I'd need the full desktop / screen.
